<?php

namespace Grim\Utils;

use Grim\Config\ConfigManager;

class DataExporter
{
    private ConfigManager $config;
    private Logger $logger;
    private string $resultsDir;

    public function __construct()
    {
        $this->config = ConfigManager::getInstance();
        $this->logger = Logger::getInstance();
        $this->resultsDir = $this->config->get('scanner.results_dir', 'results/');
        
        // Create results directory if it doesn't exist
        if (!is_dir($this->resultsDir)) {
            mkdir($this->resultsDir, 0755, true);
        }
    }

    public function exportToJson(array $data, string $filename = null): string
    {
        $filename = $filename ?: 'grim_scan_' . date('Y-m-d_H-i-s');
        $filepath = $this->resultsDir . $filename . '.json';
        
        $jsonData = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        
        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new \RuntimeException('JSON encoding failed: ' . json_last_error_msg());
        }
        
        file_put_contents($filepath, $jsonData);
        
        $this->logger->info("Results exported to JSON", ['filepath' => $filepath]);
        
        return $filepath;
    }

    public function exportToCsv(array $data, string $filename = null): string
    {
        $filename = $filename ?: 'grim_scan_' . date('Y-m-d_H-i-s');
        $filepath = $this->resultsDir . $filename . '.csv';
        
        $csvData = $this->arrayToCsv($data);
        file_put_contents($filepath, $csvData);
        
        $this->logger->info("Results exported to CSV", ['filepath' => $filepath]);
        
        return $filepath;
    }

    public function exportToHtml(array $data, string $filename = null): string
    {
        $filename = $filename ?: 'grim_scan_' . date('Y-m-d_H-i-s');
        $filepath = $this->resultsDir . $filename . '.html';
        
        $htmlData = $this->arrayToHtml($data);
        file_put_contents($filepath, $htmlData);
        
        $this->logger->info("Results exported to HTML", ['filepath' => $filepath]);
        
        return $filepath;
    }

    public function exportToXml(array $data, string $filename = null): string
    {
        $filename = $filename ?: 'grim_scan_' . date('Y-m-d_H-i-s');
        $filepath = $this->resultsDir . $filename . '.xml';
        
        $xmlData = $this->arrayToXml($data);
        file_put_contents($filepath, $xmlData);
        
        $this->logger->info("Results exported to XML", ['filepath' => $filepath]);
        
        return $filepath;
    }

    public function exportToMarkdown(array $data, string $filename = null): string
    {
        $filename = $filename ?: 'grim_scan_' . date('Y-m-d_H-i-s');
        $filepath = $this->resultsDir . $filename . '.md';
        
        $markdownData = $this->arrayToMarkdown($data);
        file_put_contents($filepath, $markdownData);
        
        $this->logger->info("Results exported to Markdown", ['filepath' => $filepath]);
        
        return $filepath;
    }

    private function arrayToCsv(array $data): string
    {
        $csv = "Type,Description,Details,Severity,Timestamp,Target\n";
        
        $this->flattenArray($data, $csv);
        
        return $csv;
    }

    private function flattenArray(array $data, string &$csv, string $prefix = ''): void
    {
        foreach ($data as $key => $value) {
            $currentKey = $prefix ? $prefix . '.' . $key : $key;
            
            if (is_array($value)) {
                $this->flattenArray($value, $csv, $currentKey);
            } else {
                $escapedValue = is_string($value) ? '"' . str_replace('"', '""', $value) . '"' : $value;
                $csv .= "{$currentKey},{$escapedValue}\n";
            }
        }
    }

    private function arrayToHtml(array $data): string
    {
        $html = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n";
        $html .= "<meta charset=\"UTF-8\">\n";
        $html .= "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
        $html .= "<title>GRIM Security Scanner Results</title>\n";
        $html .= "<style>\n";
        $html .= $this->getHtmlStyles();
        $html .= "</style>\n</head>\n<body>\n";
        
        $html .= "<div class=\"container\">\n";
        $html .= "<header>\n";
        $html .= "<h1>🔒 GRIM Security Scanner Results</h1>\n";
        $html .= "<p class=\"timestamp\">Generated: " . date('Y-m-d H:i:s T') . "</p>\n";
        $html .= "</header>\n";
        
        $html .= $this->generateHtmlContent($data);
        
        $html .= "<footer>\n";
        $html .= "<p>Generated by GRIM Security Scanner v3.0.0</p>\n";
        $html .= "</footer>\n";
        $html .= "</div>\n";
        
        $html .= "</body>\n</html>";
        
        return $html;
    }

    private function getHtmlStyles(): string
    {
        return "
            body { 
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                margin: 0; 
                padding: 0; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
            }
            .container { 
                max-width: 1200px; 
                margin: 0 auto; 
                background: white; 
                box-shadow: 0 0 20px rgba(0,0,0,0.1);
                min-height: 100vh;
            }
            header { 
                background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); 
                color: white; 
                padding: 2rem; 
                text-align: center;
            }
            header h1 { 
                margin: 0; 
                font-size: 2.5rem; 
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
            }
            .timestamp { 
                margin: 1rem 0 0 0; 
                opacity: 0.8; 
                font-size: 1.1rem;
            }
            .section { 
                margin: 2rem; 
                padding: 1.5rem; 
                border: 1px solid #e1e8ed; 
                border-radius: 8px; 
                background: #f8f9fa;
            }
            .section h2 { 
                color: #2c3e50; 
                border-bottom: 2px solid #3498db; 
                padding-bottom: 0.5rem;
                margin-top: 0;
            }
            .vulnerability { 
                background: #fee; 
                border-left: 4px solid #e74c3c; 
                padding: 1rem; 
                margin: 1rem 0; 
                border-radius: 4px;
            }
            .warning { 
                background: #fef9e7; 
                border-left: 4px solid #f39c12; 
                padding: 1rem; 
                margin: 1rem 0; 
                border-radius: 4px;
            }
            .info { 
                background: #e8f4fd; 
                border-left: 4px solid #3498db; 
                padding: 1rem; 
                margin: 1rem 0; 
                border-radius: 4px;
            }
            .severity-badge { 
                display: inline-block; 
                padding: 0.25rem 0.5rem; 
                border-radius: 12px; 
                font-size: 0.8rem; 
                font-weight: bold; 
                text-transform: uppercase;
            }
            .severity-vulnerability { background: #e74c3c; color: white; }
            .severity-warning { background: #f39c12; color: white; }
            .severity-info { background: #3498db; color: white; }
            .details { 
                background: #f8f9fa; 
                padding: 1rem; 
                border-radius: 4px; 
                margin-top: 1rem; 
                font-family: monospace; 
                font-size: 0.9rem;
                overflow-x: auto;
            }
            footer { 
                text-align: center; 
                padding: 2rem; 
                color: #7f8c8d; 
                border-top: 1px solid #ecf0f1;
                margin-top: 2rem;
            }
            .summary { 
                background: #ecf0f1; 
                padding: 1.5rem; 
                border-radius: 8px; 
                margin: 2rem;
            }
            .summary h3 { 
                margin-top: 0; 
                color: #2c3e50;
            }
            .summary-grid { 
                display: grid; 
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); 
                gap: 1rem; 
                margin-top: 1rem;
            }
            .summary-item { 
                background: white; 
                padding: 1rem; 
                border-radius: 4px; 
                text-align: center;
                border: 1px solid #bdc3c7;
            }
            .summary-number { 
                font-size: 2rem; 
                font-weight: bold; 
                color: #2c3e50;
            }
            .summary-label { 
                color: #7f8c8d; 
                font-size: 0.9rem;
            }
        ";
    }

    private function generateHtmlContent(array $data): string
    {
        $html = "";
        
        // Summary section
        if (isset($data['scanners'])) {
            $html .= "<div class=\"summary\">\n";
            $html .= "<h3>📊 Scan Summary</h3>\n";
            $html .= "<div class=\"summary-grid\">\n";
            
            $html .= "<div class=\"summary-item\">\n";
            $html .= "<div class=\"summary-number\">" . htmlspecialchars($data['target'] ?? 'N/A') . "</div>\n";
            $html .= "<div class=\"summary-label\">Target</div>\n";
            $html .= "</div>\n";
            
            $html .= "<div class=\"summary-item\">\n";
            $html .= "<div class=\"summary-number\">" . htmlspecialchars($data['duration'] ?? 'N/A') . "</div>\n";
            $html .= "<div class=\"summary-label\">Duration</div>\n";
            $html .= "</div>\n";
            
            $html .= "<div class=\"summary-item\">\n";
            $html .= "<div class=\"summary-number\">" . count($data['scanners']) . "</div>\n";
            $html .= "<div class=\"summary-label\">Scanners Used</div>\n";
            $html .= "</div>\n";
            
            $html .= "</div>\n";
            $html .= "</div>\n";
        }
        
        // Scanner results
        if (isset($data['scanners'])) {
            foreach ($data['scanners'] as $scanner => $results) {
                $html .= "<div class=\"section\">\n";
                $html .= "<h2>🔍 " . ucfirst(str_replace('_', ' ', $scanner)) . "</h2>\n";
                
                if (is_array($results)) {
                    $html .= $this->renderScannerResults($results);
                } else {
                    $html .= "<p>" . htmlspecialchars($results) . "</p>\n";
                }
                
                $html .= "</div>\n";
            }
        }
        
        return $html;
    }

    private function renderScannerResults(array $results): string
    {
        $html = "";
        
        if (isset($results[0]['severity'])) {
            // Vulnerability scan results
            foreach ($results as $result) {
                $severityClass = 'severity-' . $result['severity'];
                $severityLabel = ucfirst($result['severity']);
                
                $html .= "<div class=\"{$result['severity']}\">\n";
                $html .= "<h4>" . htmlspecialchars($result['type']) . "</h4>\n";
                $html .= "<p>" . htmlspecialchars($result['description']) . "</p>\n";
                $html .= "<span class=\"severity-badge {$severityClass}\">{$severityLabel}</span>\n";
                
                if (!empty($result['details'])) {
                    $html .= "<div class=\"details\">\n";
                    $html .= "<strong>Details:</strong><br>\n";
                    $html .= htmlspecialchars(json_encode($result['details'], JSON_PRETTY_PRINT));
                    $html .= "</div>\n";
                }
                
                $html .= "</div>\n";
            }
        } else {
            // Information gathering results
            foreach ($results as $key => $value) {
                $html .= "<h4>" . ucfirst(str_replace('_', ' ', $key)) . "</h4>\n";
                
                if (is_array($value)) {
                    $html .= "<div class=\"details\">\n";
                    $html .= htmlspecialchars(json_encode($value, JSON_PRETTY_PRINT));
                    $html .= "</div>\n";
                } else {
                    $html .= "<p>" . htmlspecialchars($value) . "</p>\n";
                }
            }
        }
        
        return $html;
    }

    private function arrayToXml(array $data): string
    {
        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        $xml .= "<grim-scan-results>\n";
        $xml .= $this->arrayToXmlRecursive($data);
        $xml .= "</grim-scan-results>";
        
        return $xml;
    }

    private function arrayToXmlRecursive(array $data, string $indent = "  "): string
    {
        $xml = "";
        
        foreach ($data as $key => $value) {
            $safeKey = preg_replace('/[^a-zA-Z0-9_-]/', '_', $key);
            
            if (is_array($value)) {
                $xml .= "{$indent}<{$safeKey}>\n";
                $xml .= $this->arrayToXmlRecursive($value, $indent . "  ");
                $xml .= "{$indent}</{$safeKey}>\n";
            } else {
                $xml .= "{$indent}<{$safeKey}>" . htmlspecialchars($value) . "</{$safeKey}>\n";
            }
        }
        
        return $xml;
    }

    private function arrayToMarkdown(array $data): string
    {
        $markdown = "# GRIM Security Scanner Results\n\n";
        $markdown .= "**Generated:** " . date('Y-m-d H:i:s T') . "\n\n";
        
        if (isset($data['target'])) {
            $markdown .= "**Target:** " . $data['target'] . "\n";
        }
        
        if (isset($data['duration'])) {
            $markdown .= "**Duration:** " . $data['duration'] . "\n\n";
        }
        
        $markdown .= "---\n\n";
        
        if (isset($data['scanners'])) {
            foreach ($data['scanners'] as $scanner => $results) {
                $markdown .= "## " . ucfirst(str_replace('_', ' ', $scanner)) . "\n\n";
                
                if (is_array($results)) {
                    $markdown .= $this->renderMarkdownResults($results);
                } else {
                    $markdown .= $results . "\n\n";
                }
            }
        }
        
        return $markdown;
    }

    private function renderMarkdownResults(array $results): string
    {
        $markdown = "";
        
        if (isset($results[0]['severity'])) {
            // Vulnerability scan results
            foreach ($results as $result) {
                $severityIcon = $this->getSeverityIcon($result['severity']);
                $markdown .= "### {$severityIcon} " . ucfirst($result['type']) . "\n\n";
                $markdown .= "**Description:** " . $result['description'] . "\n\n";
                $markdown .= "**Severity:** " . ucfirst($result['severity']) . "\n\n";
                
                if (!empty($result['details'])) {
                    $markdown .= "**Details:**\n```json\n";
                    $markdown .= json_encode($result['details'], JSON_PRETTY_PRINT);
                    $markdown .= "\n```\n\n";
                }
                
                $markdown .= "---\n\n";
            }
        } else {
            // Information gathering results
            foreach ($results as $key => $value) {
                $markdown .= "### " . ucfirst(str_replace('_', ' ', $key)) . "\n\n";
                
                if (is_array($value)) {
                    $markdown .= "```json\n";
                    $markdown .= json_encode($value, JSON_PRETTY_PRINT);
                    $markdown .= "\n```\n\n";
                } else {
                    $markdown .= $value . "\n\n";
                }
            }
        }
        
        return $markdown;
    }

    private function getSeverityIcon(string $severity): string
    {
        return match($severity) {
            'vulnerability' => '🚨',
            'warning' => '⚠️',
            'info' => 'ℹ️',
            default => '📝'
        };
    }

    public function getSupportedFormats(): array
    {
        return ['json', 'csv', 'html', 'xml', 'markdown'];
    }

    public function exportToAllFormats(array $data, string $filename = null): array
    {
        $exportedFiles = [];
        
        foreach ($this->getSupportedFormats() as $format) {
            try {
                $method = 'exportTo' . ucfirst($format);
                $filepath = $this->$method($data, $filename);
                $exportedFiles[$format] = $filepath;
            } catch (\Exception $e) {
                $this->logger->error("Failed to export to {$format}", ['error' => $e->getMessage()]);
            }
        }
        
        return $exportedFiles;
    }
}
